name: build-obs-container

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  checks: read
  contents: read
  id-token: write
  packages: write
  pull-requests: read
  statuses: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          sbom: true
          provenance: true
          push: ${{ contains(github.ref, 'refs/heads/main') || contains(github.ref, 'refs/tags/') }}
          tags: ghcr.io/${{ github.repository }}:latest

